### ISSUE TITLE
Log.h and Log.cpp do not work together

### ISSUE THREAD

**Issue by vrglab** [700Noel/Zahel#1]
![image](https://github.com/700Noel/Zahel/assets/49840103/8c75a40c-da2b-45d7-9f2b-64f51e8ca1d7)
this error's are from  the Log.h and Log.cpp files specifically the static variables `s_CoreLogger` and `s_ClientLogger`, I am unsure why but I believe because they are un-initialized it causes the compiler to go nuts.

**Comment by vrglab** [comment]
Problem solved my initial guess was correct by puting ` s_CoreLogger = spdlog::stdout_color_mt("ZAHEL");` in the Log.h file rather than the Log.cpp file it fixed it

**Comment by 700Noel** [comment]
But wait before doing the Premake stuff that worked. Even though I didn't change anything
