### ISSUE TITLE
include Zahel/Core.h written differently

### ISSUE THREAD

**Issue by 700Noel** [700Noel/Zahel#3]
Had to write #include "src/Zahel/Core.h", where as Cherno only had to write "Hazel/Core.h". Our hierachy looks same. Just wanted to know why.

![event](https://github.com/700Noel/Zahel/assets/114501947/77d40957-aca2-4619-a244-e5c9a8d999aa)

**Comment by vrglab** [comment]
Hazel has its src folder linked as a include, and because of that he doesn't need to write the src before the includes because Visual studio knows that the files we want are in the src folder, its also why Hazel can include its files using <> rather than ""
